// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"fmt"
	"time"

	"github.com/emvi/null"
)

type GenderType string

const (
	GenderTypeM GenderType = "M"
	GenderTypeF GenderType = "F"
)

func (e *GenderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GenderType(s)
	case string:
		*e = GenderType(s)
	default:
		return fmt.Errorf("unsupported scan type for GenderType: %T", src)
	}
	return nil
}

type TrainingSport string

const (
	TrainingSportRunning  TrainingSport = "running"
	TrainingSportCycling  TrainingSport = "cycling"
	TrainingSportSwimming TrainingSport = "swimming"
	TrainingSportWeight   TrainingSport = "weight"
)

func (e *TrainingSport) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TrainingSport(s)
	case string:
		*e = TrainingSport(s)
	default:
		return fmt.Errorf("unsupported scan type for TrainingSport: %T", src)
	}
	return nil
}

type TrainingStatus string

const (
	TrainingStatusNew          TrainingStatus = "new"
	TrainingStatusNotified     TrainingStatus = "notified"
	TrainingStatusOverdue      TrainingStatus = "overdue"
	TrainingStatusDone         TrainingStatus = "done"
	TrainingStatusDoneFeedback TrainingStatus = "done_feedback"
)

func (e *TrainingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TrainingStatus(s)
	case string:
		*e = TrainingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TrainingStatus: %T", src)
	}
	return nil
}

type UserType string

const (
	UserTypeAdmin   UserType = "admin"
	UserTypeCoach   UserType = "coach"
	UserTypeAthlete UserType = "athlete"
)

func (e *UserType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserType(s)
	case string:
		*e = UserType(s)
	default:
		return fmt.Errorf("unsupported scan type for UserType: %T", src)
	}
	return nil
}

type Training struct {
	ID        int64          `json:"id"`
	UserID    int64          `json:"user_id"`
	Date      time.Time      `json:"date"`
	Sport     TrainingSport  `json:"sport"`
	Type      null.String    `json:"type"`
	Intensity null.String    `json:"intensity"`
	Details   string         `json:"details"`
	Status    TrainingStatus `json:"status"`
	CreatedAt time.Time      `json:"created_at"`
	DeletedAt null.Time      `json:"deleted_at"`
}

type TrainingFeedback struct {
	ID         int64 `json:"id"`
	TrainingID int64 `json:"training_id"`
	BorgScale  int32 `json:"borg_scale"`
}

type User struct {
	ID        int64       `json:"id"`
	Type      UserType    `json:"type"`
	Name      string      `json:"name"`
	Gender    GenderType  `json:"gender"`
	Email     string      `json:"email"`
	Phone     null.String `json:"phone"`
	Birth     null.Time   `json:"birth"`
	Active    bool        `json:"active"`
	CreatedAt time.Time   `json:"created_at"`
	DeletedAt null.Time   `json:"deleted_at"`
}
