// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateTraining(ctx context.Context, arg CreateTrainingParams) (Training, error)
	CreateTrainingFeedback(ctx context.Context, arg CreateTrainingFeedbackParams) (TrainingFeedback, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTraining(ctx context.Context, id int64) error
	DeleteTrainingFeedback(ctx context.Context, trainingID int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetTraining(ctx context.Context, id int64) (Training, error)
	GetTrainingFeedback(ctx context.Context, trainingID int64) (TrainingFeedback, error)
	GetUser(ctx context.Context, id int64) (User, error)
	ListActiveUsers(ctx context.Context, arg ListActiveUsersParams) ([]User, error)
	ListAllUsers(ctx context.Context, arg ListAllUsersParams) ([]User, error)
	ListTrainingFeedbacksByUser(ctx context.Context, userID int64) ([]TrainingFeedback, error)
	ListTrainingFeedbacksByUserInPeriod(ctx context.Context, arg ListTrainingFeedbacksByUserInPeriodParams) ([]TrainingFeedback, error)
	ListTrainingsByUser(ctx context.Context, userID int64) ([]Training, error)
	ListTrainingsByUserInPeriod(ctx context.Context, arg ListTrainingsByUserInPeriodParams) ([]Training, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateTraining(ctx context.Context, arg UpdateTrainingParams) (Training, error)
	UpdateTrainingFeedback(ctx context.Context, arg UpdateTrainingFeedbackParams) (TrainingFeedback, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
