// Code generated by sqlc. DO NOT EDIT.
// source: training_feedback.sql

package db

import (
	"context"
	"time"
)

const createTrainingFeedback = `-- name: CreateTrainingFeedback :one
INSERT INTO training_feedback (training_id, borg_scale)
VALUES ($1, $2)
RETURNING id, training_id, borg_scale
`

type CreateTrainingFeedbackParams struct {
	TrainingID int64 `json:"training_id"`
	BorgScale  int32 `json:"borg_scale"`
}

func (q *Queries) CreateTrainingFeedback(ctx context.Context, arg CreateTrainingFeedbackParams) (TrainingFeedback, error) {
	row := q.db.QueryRowContext(ctx, createTrainingFeedback, arg.TrainingID, arg.BorgScale)
	var i TrainingFeedback
	err := row.Scan(&i.ID, &i.TrainingID, &i.BorgScale)
	return i, err
}

const deleteTrainingFeedback = `-- name: DeleteTrainingFeedback :exec
DELETE
FROM training_feedback
WHERE training_id = $1
`

func (q *Queries) DeleteTrainingFeedback(ctx context.Context, trainingID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTrainingFeedback, trainingID)
	return err
}

const getTrainingFeedback = `-- name: GetTrainingFeedback :one
SELECT id, training_id, borg_scale
FROM training_feedback
WHERE training_id = $1
LIMIT 1
`

func (q *Queries) GetTrainingFeedback(ctx context.Context, trainingID int64) (TrainingFeedback, error) {
	row := q.db.QueryRowContext(ctx, getTrainingFeedback, trainingID)
	var i TrainingFeedback
	err := row.Scan(&i.ID, &i.TrainingID, &i.BorgScale)
	return i, err
}

const listTrainingFeedbacksByUser = `-- name: ListTrainingFeedbacksByUser :many
SELECT tf.id, tf.training_id, tf.borg_scale
FROM training_feedback tf
         JOIN training t ON tf.training_id = t.id
WHERE t.user_id = $1
  AND t.deleted_at IS NULL
ORDER BY tf.id
`

func (q *Queries) ListTrainingFeedbacksByUser(ctx context.Context, userID int64) ([]TrainingFeedback, error) {
	rows, err := q.db.QueryContext(ctx, listTrainingFeedbacksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrainingFeedback{}
	for rows.Next() {
		var i TrainingFeedback
		if err := rows.Scan(&i.ID, &i.TrainingID, &i.BorgScale); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainingFeedbacksByUserInPeriod = `-- name: ListTrainingFeedbacksByUserInPeriod :many
SELECT tf.id, tf.training_id, tf.borg_scale
FROM training_feedback tf
         JOIN training t ON tf.training_id = t.id
WHERE t.user_id = $1
  AND date between $2 AND $3
  AND t.deleted_at IS NULL
ORDER BY tf.id
`

type ListTrainingFeedbacksByUserInPeriodParams struct {
	UserID int64     `json:"user_id"`
	Date   time.Time `json:"date"`
	Date_2 time.Time `json:"date_2"`
}

func (q *Queries) ListTrainingFeedbacksByUserInPeriod(ctx context.Context, arg ListTrainingFeedbacksByUserInPeriodParams) ([]TrainingFeedback, error) {
	rows, err := q.db.QueryContext(ctx, listTrainingFeedbacksByUserInPeriod, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrainingFeedback{}
	for rows.Next() {
		var i TrainingFeedback
		if err := rows.Scan(&i.ID, &i.TrainingID, &i.BorgScale); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrainingFeedback = `-- name: UpdateTrainingFeedback :one
UPDATE training_feedback
SET borg_scale = $2
WHERE training_id = $1
RETURNING id, training_id, borg_scale
`

type UpdateTrainingFeedbackParams struct {
	TrainingID int64 `json:"training_id"`
	BorgScale  int32 `json:"borg_scale"`
}

func (q *Queries) UpdateTrainingFeedback(ctx context.Context, arg UpdateTrainingFeedbackParams) (TrainingFeedback, error) {
	row := q.db.QueryRowContext(ctx, updateTrainingFeedback, arg.TrainingID, arg.BorgScale)
	var i TrainingFeedback
	err := row.Scan(&i.ID, &i.TrainingID, &i.BorgScale)
	return i, err
}
