// Code generated by sqlc. DO NOT EDIT.
// source: training.sql

package db

import (
	"context"
	"time"

	"github.com/emvi/null"
)

const createTraining = `-- name: CreateTraining :one
INSERT INTO training (user_id, date, sport, type, intensity, details, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, date, sport, type, intensity, details, status, created_at, deleted_at
`

type CreateTrainingParams struct {
	UserID    int64          `json:"user_id"`
	Date      time.Time      `json:"date"`
	Sport     TrainingSport  `json:"sport"`
	Type      null.String    `json:"type"`
	Intensity null.String    `json:"intensity"`
	Details   string         `json:"details"`
	Status    TrainingStatus `json:"status"`
}

func (q *Queries) CreateTraining(ctx context.Context, arg CreateTrainingParams) (Training, error) {
	row := q.db.QueryRowContext(ctx, createTraining,
		arg.UserID,
		arg.Date,
		arg.Sport,
		arg.Type,
		arg.Intensity,
		arg.Details,
		arg.Status,
	)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Sport,
		&i.Type,
		&i.Intensity,
		&i.Details,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteTraining = `-- name: DeleteTraining :exec
UPDATE training
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) DeleteTraining(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTraining, id)
	return err
}

const getTraining = `-- name: GetTraining :one
SELECT id, user_id, date, sport, type, intensity, details, status, created_at, deleted_at
FROM training
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetTraining(ctx context.Context, id int64) (Training, error) {
	row := q.db.QueryRowContext(ctx, getTraining, id)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Sport,
		&i.Type,
		&i.Intensity,
		&i.Details,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTrainingsByUser = `-- name: ListTrainingsByUser :many
SELECT id, user_id, date, sport, type, intensity, details, status, created_at, deleted_at
FROM training
WHERE user_id = $1
ORDER BY id
`

func (q *Queries) ListTrainingsByUser(ctx context.Context, userID int64) ([]Training, error) {
	rows, err := q.db.QueryContext(ctx, listTrainingsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Training{}
	for rows.Next() {
		var i Training
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.Sport,
			&i.Type,
			&i.Intensity,
			&i.Details,
			&i.Status,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainingsByUserInPeriod = `-- name: ListTrainingsByUserInPeriod :many
SELECT id, user_id, date, sport, type, intensity, details, status, created_at, deleted_at
FROM training
WHERE user_id = $1
  AND date between $2 AND $3
  AND deleted_at IS NULL
ORDER BY id
`

type ListTrainingsByUserInPeriodParams struct {
	UserID int64     `json:"user_id"`
	Date   time.Time `json:"date"`
	Date_2 time.Time `json:"date_2"`
}

func (q *Queries) ListTrainingsByUserInPeriod(ctx context.Context, arg ListTrainingsByUserInPeriodParams) ([]Training, error) {
	rows, err := q.db.QueryContext(ctx, listTrainingsByUserInPeriod, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Training{}
	for rows.Next() {
		var i Training
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.Sport,
			&i.Type,
			&i.Intensity,
			&i.Details,
			&i.Status,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTraining = `-- name: UpdateTraining :one
UPDATE training
SET date      = $2,
    sport     = $3,
    type      = $4,
    intensity = $5,
    details   = $6,
    status    = $7
WHERE id = $1
RETURNING id, user_id, date, sport, type, intensity, details, status, created_at, deleted_at
`

type UpdateTrainingParams struct {
	ID        int64          `json:"id"`
	Date      time.Time      `json:"date"`
	Sport     TrainingSport  `json:"sport"`
	Type      null.String    `json:"type"`
	Intensity null.String    `json:"intensity"`
	Details   string         `json:"details"`
	Status    TrainingStatus `json:"status"`
}

func (q *Queries) UpdateTraining(ctx context.Context, arg UpdateTrainingParams) (Training, error) {
	row := q.db.QueryRowContext(ctx, updateTraining,
		arg.ID,
		arg.Date,
		arg.Sport,
		arg.Type,
		arg.Intensity,
		arg.Details,
		arg.Status,
	)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Sport,
		&i.Type,
		&i.Intensity,
		&i.Details,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
