// Code generated by sqlc. DO NOT EDIT.
// source: user.sql

package db

import (
	"context"

	"github.com/emvi/null"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (type, name, gender, email, phone, birth, active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, type, name, gender, email, phone, birth, active, created_at, deleted_at
`

type CreateUserParams struct {
	Type   UserType    `json:"type"`
	Name   string      `json:"name"`
	Gender GenderType  `json:"gender"`
	Email  string      `json:"email"`
	Phone  null.String `json:"phone"`
	Birth  null.Time   `json:"birth"`
	Active bool        `json:"active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Type,
		arg.Name,
		arg.Gender,
		arg.Email,
		arg.Phone,
		arg.Birth,
		arg.Active,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Gender,
		&i.Email,
		&i.Phone,
		&i.Birth,
		&i.Active,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, type, name, gender, email, phone, birth, active, created_at, deleted_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Gender,
		&i.Email,
		&i.Phone,
		&i.Birth,
		&i.Active,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveUsers = `-- name: ListActiveUsers :many
SELECT id, type, name, gender, email, phone, birth, active, created_at, deleted_at
FROM users
WHERE deleted_at IS NULL
  AND active = TRUE
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListActiveUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListActiveUsers(ctx context.Context, arg ListActiveUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listActiveUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Gender,
			&i.Email,
			&i.Phone,
			&i.Birth,
			&i.Active,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, type, name, gender, email, phone, birth, active, created_at, deleted_at
FROM users
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListAllUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllUsers(ctx context.Context, arg ListAllUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listAllUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Gender,
			&i.Email,
			&i.Phone,
			&i.Birth,
			&i.Active,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, type, name, gender, email, phone, birth, active, created_at, deleted_at
FROM users
WHERE deleted_at IS NULL
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Gender,
			&i.Email,
			&i.Phone,
			&i.Birth,
			&i.Active,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET type   = $2,
    name   = $3,
    gender = $4,
    email  = $5,
    phone  = $6,
    birth  = $7,
    active = $8
WHERE id = $1
RETURNING id, type, name, gender, email, phone, birth, active, created_at, deleted_at
`

type UpdateUserParams struct {
	ID     int64       `json:"id"`
	Type   UserType    `json:"type"`
	Name   string      `json:"name"`
	Gender GenderType  `json:"gender"`
	Email  string      `json:"email"`
	Phone  null.String `json:"phone"`
	Birth  null.Time   `json:"birth"`
	Active bool        `json:"active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Type,
		arg.Name,
		arg.Gender,
		arg.Email,
		arg.Phone,
		arg.Birth,
		arg.Active,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Gender,
		&i.Email,
		&i.Phone,
		&i.Birth,
		&i.Active,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
